http:
  middlewares:
    https-force:
      redirectScheme:
        scheme: https
        permanent: true
    ddos-ratelimit:
      rateLimit:
        average: 1
        burst: 3
  routers:
    web_proit-co-id:
      rule: "Host(`proit.co.id`)"
      service: web_proit-co-id
      entryPoints:
        - websecure
      tls:
        certresolver: letsencrypt

  services:
    web_proit-co-id:
      loadBalancer:
        servers:
          - url: "http://backend.proit.co.id:8000"
