version: "3.3"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/docker/swarm/traefik/prometheus/:/etc/prometheus/
      - /opt/docker/swarm/traefik/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=1024MB'
    deploy:
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.routers.prometheus.middlewares=traefik-auth"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: traefik-net
